import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../contexts/AuthContext.jsx";
import { getAnnouncements, getProgress, getResults } from "../services/dataService.js";
import { MODULE_CATALOG } from "../data/moduleCatalog.js";
import PageHeader from "../components/PageHeader.jsx";
import StatCard from "../components/StatCard.jsx";
import Icon from "../components/Icon.jsx";
const actions=[['/modules','book','eModul IKR','Nota, video, PDF dan topik'],['/quiz','quiz','Kuiz Online','Random soalan, timer dan auto-marking'],['/ai-tutor','ai','AI Tutor','Bantuan OSI, subnetting, VLAN dan routing'],['/chat','chat','Chat Kelas','Perbincangan dan pengumuman'],['/scores','progress','Markah Saya','Rekod keputusan kuiz'],['/ranking','ranking','Ranking','Kedudukan berdasarkan prestasi']];
export default function StudentDashboard(){const{user}=useAuth();const[ann,setAnn]=useState([]);const[results,setResults]=useState([]);useEffect(()=>{getAnnouncements().then(setAnn);getResults().then(r=>setResults(r.filter(x=>x.studentId===user.uid)))},[user.uid]);const progress=getProgress(user.uid);const completed=Object.values(progress).reduce((n,a)=>n+a.length,0);return <><PageHeader eyebrow="Dashboard pelajar" title={`Selamat datang, ${user.name}`} description="Teruskan pembelajaran dan pantau prestasi anda dari satu ruang kerja."/><div className="grid gap-4 md:grid-cols-3"><StatCard icon="book" label="Modul tersedia" value={MODULE_CATALOG.length} hint="IKR3013 hingga IKR3133"/><StatCard icon="quiz" label="Percubaan kuiz" value={results.length} hint="Keputusan tersimpan mengikut akaun"/><StatCard icon="progress" label="Topik selesai" value={completed} hint="Progress pembelajaran semasa"/></div><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{actions.map(([to,icon,title,desc])=><Link key={to} to={to} className="panel group p-5 transition hover:-translate-y-1 hover:border-tech-500"><div className="flex items-center justify-between"><div className="rounded-xl bg-tech-500/10 p-3 text-tech-600"><Icon name={icon}/></div><Icon name="arrow" className="text-slate-400 transition group-hover:translate-x-1 group-hover:text-tech-600"/></div><h2 className="mt-5 text-lg font-black">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{desc}</p></Link>)}</div><section className="panel mt-7 p-6"><div className="flex items-center justify-between"><h2 className="text-lg font-black">Pengumuman terkini</h2><Link to="/chat" className="text-sm font-bold text-tech-600">Buka komunikasi</Link></div><div className="mt-4 space-y-3">{ann.slice(0,3).map(a=><article key={a.id} className="rounded-xl bg-slate-50 p-4 dark:bg-white/5"><div className="font-bold">{a.title}</div><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{a.body}</p></article>)}</div></section></>}
